export interface Recipe {
  id: number
  name: string
  category: "pasta" | "soup" | "dessert" | "meat" | "asian" | "appetizer"
  difficulty: "low" | "medium" | "high"
  prepTime: number // in minutes
  cookTime: number // in minutes
  servings: number
  tags: string[]
  ingredients: string[]
  steps: string[]
  accompaniments?: string
}

export const recipes: Recipe[] = [
  {
    id: 1,
    name: "Pasta Carbonara",
    category: "pasta",
    difficulty: "medium",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    tags: ["rápida", "clásica"],
    ingredients: [
      "400g de pasta (spaghetti o linguine)",
      "200g de guanciale o panceta",
      "4 huevos",
      "100g de queso Pecorino Romano",
      "Sal y pimienta negra",
      "Aceite de oliva",
    ],
    steps: [
      "Calienta agua con sal en una olla grande y hierve la pasta según las indicaciones del paquete.",
      "Mientras tanto, corta el guanciale en cubos pequeños y fríelo en una sartén a fuego medio-alto hasta que esté crujiente.",
      "En un cuenco, bate los huevos con el queso rallado, sal y pimienta.",
      "Cuando la pasta esté al dente, reserva una taza de agua de cocción y escúrrela.",
      "Agrega la pasta caliente a la sartén con el guanciale (sin apagar el fuego).",
      "Retira del fuego y vierte rápidamente la mezcla de huevo mientras revuelves constantemente. Agrega agua de cocción si es necesario para crear una salsa cremosa.",
      "Sirve inmediatamente con pimienta negra fresca.",
    ],
    accompaniments: "Vino blanco seco, ensalada verde fresca",
  },
  {
    id: 2,
    name: "Tacos al Pastor",
    category: "meat",
    difficulty: "high",
    prepTime: 20,
    cookTime: 20,
    servings: 4,
    tags: ["mexicana", "popular"],
    ingredients: [
      "800g de carne de cerdo",
      "4 guajillos secos",
      "3 ancho secos",
      "1/2 taza de vinagre blanco",
      "1/4 taza de achiote",
      "1 piña pequeña",
      "Tortillas de maíz",
      "Cebolla blanca",
      "Cilantro fresco",
      "Limones",
    ],
    steps: [
      "Hidrata los chiles guajillo y ancho en agua caliente durante 10 minutos.",
      "Licúa los chiles hidratados con vinagre, achiote, ajo y comino.",
      "Corta la carne de cerdo en rebanadas delgadas y marinala en la salsa preparada durante 2 horas o toda la noche si es posible.",
      "Calienta una sartén o plancha a fuego alto y cocina la carne marinada en tandas hasta que esté dorada y crujiente.",
      "Corta la piña en cubos pequeños y caliéntala en la misma sartén.",
      "Calienta las tortillas y arma los tacos con la carne, piña, cebolla y cilantro.",
      "Sirve con limones para exprimirlos sobre los tacos.",
    ],
    accompaniments: "Salsa verde, cebollitas asadas, cerveza fría",
  },
  {
    id: 3,
    name: "Ceviche Peruano",
    category: "appetizer",
    difficulty: "medium",
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    tags: ["refrescante", "económica"],
    ingredients: [
      "800g de pescado blanco fresco",
      "1 taza de jugo de limón fresco",
      "3 cebollas rojas medianas",
      "4 ajíes verdes frescos",
      "2 dientes de ajo",
      "Cilantro fresco",
      "Sal y pimienta",
      "Camote cocido",
      "Maíz morado cocido",
      "Lechuga",
    ],
    steps: [
      "Corta el pescado en cubos medianos y colócalos en un cuenco.",
      "Vierte el jugo de limón fresco sobre el pescado y revuelve bien.",
      "Deja reposar durante 15-20 minutos para que el pescado se 'cocine' en el limón.",
      "Mientras tanto, pica la cebolla en media luna fina y colócala en agua fría con sal durante 10 minutos.",
      "Prepara una salsa licuando los ajíes verdes con ajo, cilantro, sal y un poco de caldo de pescado.",
      "Escurre la cebolla y agrégala al pescado junto con la salsa de ají.",
      "Sirve en una cama de lechuga, acompañado de camote y maíz morado.",
    ],
    accompaniments: "Cerveza blanca helada, tostadas de maíz",
  },
  {
    id: 4,
    name: "Risotto de Champiñones",
    category: "pasta",
    difficulty: "medium",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    tags: ["elegante", "vegetariana"],
    ingredients: [
      "300g de arroz Arborio",
      "400g de champiñones frescos",
      "1 cebolla pequeña",
      "2 dientes de ajo",
      "1 taza de vino blanco",
      "1 litro de caldo de verduras caliente",
      "50g de queso Parmesano",
      "50g de mantequilla",
      "Aceite de oliva",
      "Sal, pimienta y tomillo",
    ],
    steps: [
      "Limpia los champiñones y córtalos en láminas. Calienta 2 cucharadas de aceite en una sartén y dóralos. Reserva.",
      "En una olla grande, calienta 2 cucharadas de aceite de oliva y sofríe la cebolla y ajo picados hasta que estén suaves.",
      "Agrega el arroz y tuesta durante 2-3 minutos revolviendo constantemente.",
      "Vierte el vino blanco y espera a que se absorba completamente.",
      "Comienza a agregar el caldo caliente, una taza a la vez, revolviendo frecuentemente. Espera a que cada porción se absorba antes de agregar la siguiente.",
      "Continúa este proceso durante unos 18-20 minutos hasta que el arroz esté cremoso pero al dente.",
      "Agrega los champiñones cocinados, mantequilla y queso Parmesano. Sazona con sal, pimienta y tomillo.",
      "Sirve inmediatamente con más queso Parmesano rallado.",
    ],
    accompaniments: "Vino blanco frío, pan tostado con ajo",
  },
  {
    id: 5,
    name: "Bibimbap Coreano",
    category: "asian",
    difficulty: "high",
    prepTime: 25,
    cookTime: 20,
    servings: 2,
    tags: ["asiática", "colorida"],
    ingredients: [
      "2 tazas de arroz cocido",
      "200g de carne molida de res",
      "2 cucharadas de salsa de soja",
      "1 cucharada de aceite de sésamo",
      "2 zanahorias medianas",
      "200g de espinacas frescas",
      "150g de champiñones",
      "1 pepino pequeño",
      "2 huevos",
      "2 cucharadas de pasta de gochujang",
      "Semillas de sésamo",
      "Aceite vegetal",
    ],
    steps: [
      "Condimenta y cocina la carne molida en una sartén con salsa de soja y ajo. Reserva.",
      "Saltea separadamente: zanahorias juliana, espinacas escaldadas, champiñones laminados y pepino. Condimenta cada uno con sal, ajo y un poco de aceite de sésamo.",
      "Divide el arroz cocido entre dos boles de cerámica.",
      "Arregla todos los vegetales y la carne alrededor del arroz en el bol de forma ordenada.",
      "Fríe los huevos con las claras cuajadas pero yema líquida.",
      "Coloca un huevo frito en el centro de cada bol.",
      "Mezcla la pasta gochujang con aceite de sésamo para crear una salsa.",
      "Sirve los bowls calientes con la salsa al lado y semillas de sésamo esparcidas por encima.",
      "Revuelve todo bien antes de comer.",
    ],
    accompaniments: "Té verde frío, encurtidos coreanos",
  },
  {
    id: 6,
    name: "Croissants Caseros",
    category: "dessert",
    difficulty: "high",
    prepTime: 60,
    cookTime: 25,
    servings: 12,
    tags: ["panadería", "casera"],
    ingredients: [
      "500g de harina de trigo",
      "10g de sal",
      "50g de azúcar",
      "10g de levadura fresca",
      "300ml de leche tibia",
      "250g de mantequilla fría",
      "Mantequilla derretida para barnizar",
      "Huevo para el glaseado",
    ],
    steps: [
      "Mezcla harina, sal y azúcar. Disuelve la levadura en leche tibia y agrega a la harina.",
      "Amasa hasta obtener una masa suave. Coloca en un cuenco, cubre y deja reposar 1 hora.",
      "Estira la masa en un rectángulo y coloca la mantequilla fría en el centro. Envuelve y presiona.",
      "Realiza los pliegues de hojaldre: estira 3 veces, dobla en 3 partes y refrigera 30 minutos entre cada pliegue.",
      "Después del último pliegue, refrigera durante 2 horas.",
      "Estira la masa a 3mm de grosor, corta triángulos isósceles y enrolla desde la base hacia la punta.",
      "Coloca los croissants en una bandeja, cubre y deja leudar 2 horas a temperatura ambiente.",
      "Barniza con huevo batido y hornea a 200°C durante 20-25 minutos hasta que estén dorados.",
    ],
    accompaniments: "Café espresso, mermelada de frambuesa",
  },
  {
    id: 7,
    name: "Sopa Tom Yum",
    category: "soup",
    difficulty: "medium",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    tags: ["tailandesa", "picante"],
    ingredients: [
      "1 litro de caldo de pollo",
      "400g de camarones grandes",
      "3 tallos de hierba de limón",
      "4 hojas de lima kaffir",
      "3-4 chiles rojos frescos",
      "4 cucharadas de pasta de tamarindo",
      "200g de champiñones",
      "1 cebolla roja pequeña",
      "200ml de leche de coco",
      "3 cucharadas de salsa de pescado",
      "Cilantro fresco y tomates cherry",
    ],
    steps: [
      "Calienta el caldo de pollo en una olla grande.",
      "Agrega los tallos de hierba de limón ligeramente golpeados, las hojas de lima kaffir y los chiles enteros.",
      "Lleva a ebullición y agrega la pasta de tamarindo, removiendo bien.",
      "Incorpora los camarones, champiñones laminados y cebolla en rodajas.",
      "Cocina hasta que los camarones cambien de color, aproximadamente 5-7 minutos.",
      "Agrega la leche de coco y la salsa de pescado.",
      "Prueba y ajusta los sabores: amargo (tamarindo), salado (salsa de pescado), picante (chiles) y ácido (lima).",
      "Sirve caliente decorado con cilantro fresco y tomates cherry.",
    ],
    accompaniments: "Arroz blanco, refresco de mango",
  },
  {
    id: 8,
    name: "Tiramisú Italiano",
    category: "dessert",
    difficulty: "low",
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    tags: ["italiana", "clásica"],
    ingredients: [
      "6 yemas de huevo",
      "150g de azúcar",
      "500g de mascarpone",
      "300ml de café fuerte frío",
      "3 cucharadas de licor de café (Kahlúa o similar)",
      "300g de biscochos Savoiardi",
      "Cacao en polvo sin azúcar",
      "Virutas de chocolate oscuro",
    ],
    steps: [
      "Bate las yemas de huevo con el azúcar en un cuenco hasta que esté pálido y espumoso.",
      "Agrega el mascarpone poco a poco, batiendo suavemente hasta que esté bien incorporado y cremoso.",
      "Mezcla el café frío con el licor de café.",
      "Sumerge rápidamente cada biscocho en la mezcla de café y colócalos en una capa en un molde rectangular.",
      "Extiende la mitad de la crema de mascarpone sobre los bizcochos.",
      "Repite las capas: biscochos remojados, crema de mascarpone.",
      "Cubre y refrigera durante al menos 6 horas o preferiblemente toda la noche.",
      "Antes de servir, espolvorea abundantemente con cacao en polvo y virutas de chocolate oscuro.",
    ],
    accompaniments: "Espresso caliente, vino dulce tipo Moscato",
  },
]

export const categoryIcons: Record<Recipe["category"], string> = {
  pasta: "🍝",
  soup: "🍲",
  dessert: "🍰",
  meat: "🍖",
  asian: "🥢",
  appetizer: "🥗",
}

export const difficultyLabels: Record<Recipe["difficulty"], string> = {
  low: "Fácil",
  medium: "Media",
  high: "Difícil",
}
